### ISSUE TITLE
Annotation release-based gene name maps

### ISSUE THREAD

**Issue by davidsebfischer** [theislab/sfaira#481]
Roadmap:
- We will limit ourselves to the annotation providers gencode and ensembl for now.
- We will try to stay ID centric where possible, ie route mappings through IDs.

Basic improvements to current scRNA-seq processing:

- [ ] Include annotation release into data set meta data
- [ ] Enable automatic inference of annotation release based on raw data if meta data item is not set
- [ ] Given gene `symbols` guess `provider, release`
- [ ] Given gene `symbols` in annotation `provider A, release X` yield gene `IDs` in 
- [ ] Given gene `IDs` in annotation `provider A, release X` yield gene `IDs` in `provider B, release Y`

To deal with transcript IDs and protein IDs (eg for CITE-seq):

- [ ] Given transcript `symbols` in annotation `provider A, release X` yield gene `IDs` in `provider A, release X`
- [ ] Given protein `symbols` in annotation `provider A, release X` yield gene `IDs` in `provider A, release X`
- [ ] Given transcript `IDs` in annotation `provider A, release X` yield gene `IDs` in `provider B, release Y`
- [ ] Given protein `IDs` in annotation `provider A, release X` yield gene `IDs` in `provider B, release Y`

**Comment by inecik** [comment]
## Explanation

- Below code will be able to convert IDs (it can be ensembl_ids, gencode_ids, transcript_name, gene_name -a.k.a gene symbols-, protein_name, uniprot ids, refseq gene, refseq transcript, refseq protein, PDB, HGNC, many many more!) to requested `IDs` of a requested `provider` of requested `release`. 
- Automatically infers the input `ID`s release and provider. 
- Uses a graph based on ensembl IDs for moving through history of annotations.
- It is not complete yet but most important parts (like finding correct databases, creating a graph) are ready and tested. Backbone of the conversion procedure can be found as pseudocode in 'Controller' at the end of the code. After this, I just need to spend some few time to finish up the functions, and test the script on some data.
- For transcript input IDs, target format can be gene, peptide. For peptide input IDs, target format can be gene, transcript. But for gene input IDs, the final format can only be gene. Basically because there are many proteins, transcripts of a given gene and no selection criteria has been implemented.

## Script
```
#!/usr/bin/env python3

# Kemal Inecik
# k.inecik@gmail.com

import socket
import requests
import os
import sys
import ftplib
import networkx as nx
import gzip
import pandas as pd


class DB:
    """
    Keeps some variables shared across different classes.
    """

    databases = {
        # Below two is crucial for creating the graph.
        "stable_id_event.txt.gz": {"header": ["old_stable_id", "old_version", "new_stable_id",
                                              "new_version", "mapping_session_id", "type", "score"]},
        "mapping_session.txt.gz": {"header": ["mapping_session_id", "old_db_name", "new_db_name", "old_release",
                                              "new_release", "old_assembly", "new_assembly", "created"]},
        # Below file does not contain latest relations between gene-trancript-protein.
        "gene_archive.txt.gz": {"header": ["gene_stable_id", "gene_version",
                                           "transcript_stable_id", "transcript_version",
                                           "translation_stable_id", "translation_version",
                                           "peptide_archive_id", "mapping_session_id"]},
        # Gene, transcription, and translation (peptide / protein) databases
        "gene.txt.gz": {"header": ["gene_id", "biotype", "analysis_id", "seq_region_id", "seq_region_start",
                                   "seq_region_end", "seq_region_strand", "display_xref_id", "source",
                                   "description", "is_current", "canonical_transcript_id", "stable_id",
                                   "version", "created_date", "modified_date"]},
        "transcript.txt.gz": {"header": ["transcript_id", "gene_id", "analysis_id", "seq_region_id",
                                         "seq_region_start", "seq_region_end", "seq_region_strand",
                                         "display_xref_id", "source", "biotype", "description",
                                         "is_current", "canonical_translation_id",
                                         "stable_id", "version", "created_date", "modified_date"]},
        "translation.txt.gz": {"header": ["translation_id", "transcript_id", "seq_start",
                                          "start_exon_id", "seq_end", "end_exon_id",
                                          "stable_id", "version", "created_date", "modified_date"]},
        # Accessory databases to fetch relevant information.
        "object_xref.txt.gz": {"header": ["object_xref_id", "ensembl_id", "ensembl_object_type",
                                          "xref_id", "linkage_annotation", "analysis_id"]},
        "xref.txt.gz": {"header": ["xref_id", "external_db_id", "dbprimary_acc", "display_label",
                                   "version", "description", "info_type", "info_text"]},
        "identity_xref.txt.gz": {"header": ["object_xref_id", "xref_identity", "ensembl_identity", "xref_start",
                                            "xref_end", "ensembl_start", "ensembl_end",
                                            "cigar_line", "score", "evalue"]},
        "external_db.txt.gz": {"header": ["external_db_id", "db_name", "db_release", "status",
                                          "priority", "db_display_name", "type", "secondary_db_name",
                                          "secondary_db_table", "description"]},
        "external_synonym.txt.gz": {"header": ["xref_id", "synonym"]
                                    # Note DB.databases are edited when a file is dowloaded
                                    # by DatabaseManager.get_raw_db() or by .download_db()
                                    # f"local_path_{self.organism}_{self.ensembl_release}": str,
                                    },
    }
    # Delimiter for above databases
    delimiter = "\t"

    # FTP server from which the above dataases will be downloaded.
    ensembl_ftp_base = "ftp.ensembl.org"
    @staticmethod
    def ensembl_ftp_extension(ensembl_release):
        return f"pub/release-{ensembl_release}/mysql"

    # Ensembl REST API to fetch information of organisms and latest releases.
    rest_server_api = "https://rest.ensembl.org"
    rest_server_ext = "/info/species?"

    # Lower limit the ensembl_release searching, upper limit is always the latest release: 105 as of 01.02.2022
    earliest_ensembl_release = 65


class VerifyDatabase:
    """
    - Contains function to fetch the species info from the Rest Api.
    - It is main aim is to get whether a new Ensembl release is published or not.
    - Makes it possible to enter (by the user) organism_name much more flexible.
    - Checks available ensembl releases of a given organism. Checks whether FTP server file structure is as expected.
    In very early releases, file structure is different (not a problem after ensembl_release 65 though).
    """

    def __init__(self, organism_input_name: str):
        self._unambiguous_name = "Unambiguous organism name"
        self.organism_input_name = organism_input_name
        self.all_name_synonyms, self.all_latest_release = self.fetch_organism_and_latest_release()
        self.organism_database_name = self.get_organism_database_name(self.organism_input_name)
        self.latest_ensembl_release = self.all_latest_release[self.organism_database_name]
        assert self.latest_ensembl_release > DB.earliest_ensembl_release

    def get_organism_database_name(self, query_organism):
        organism_database_name = self.all_name_synonyms[query_organism]
        if organism_database_name == self._unambiguous_name:
            raise ValueError(f"{self._unambiguous_name}: There are multiple entries in Ensembl database.")
        return organism_database_name

    def fetch_organism_and_latest_release(self):
        with requests.Session() as session:
            r = session.get(DB.rest_server_api + DB.rest_server_ext, headers={"Content-Type": "application/json"})
            if not r.ok:
                r.raise_for_status()
                sys.exit()
            decoded = r.json()["species"]
        name_synonyms = dict()
        latest_release = dict()
        for d in decoded:
            assert "core" in d["groups"]
            latest_release[d["name"]] = d["release"]
            synonyms = [d["common_name"], d["name"], d["taxon_id"], d["accession"], d["assembly"]] + d["aliases"]
            for i in list(set(synonyms)):
                if i and i in name_synonyms:
                    name_synonyms[i] = self._unambiguous_name
                elif i:
                    name_synonyms[i] = d["name"]
        return name_synonyms, latest_release


    @staticmethod
    def only_keep_dir(morg, session_ftp):
            """
            Some cases (like mus_musculus release 89) has a problem: there are multiple entries starting same. Only one
            is actually folder, the other is .gzipped version of the folder.
            """
            korg = list()
            for o in morg: 
                try:  # Note: A way to check a path is a file or folder at FTP server.
                    session_ftp.size(o)  # if it is a file, no error is raised.
                except ftplib.error_perm:
                    korg.append(o)  # if it is a folder.
            return korg

    def find_available_releases(self, verbose=False):
        
        proper_directory_structure = list()
        errors = dict()
        try:
            with ftplib.FTP(DB.ensembl_ftp_base, user="anonymous", passwd="", timeout=30) as session:
                for i in range(self.latest_ensembl_release, DB.earliest_ensembl_release, -1):
                    if verbose:
                        print(i)
                    ext = DB.ensembl_ftp_extension(i)
                    # We are only interested in the databases in 'homo_sapiens_core_*.
                    # '*' is there because it is difficult and not necessary to hard code since this part is 
                    # genome assembly and different across organisms / ensembl releases.
                    org = session.nlst(f"{ext}/{self.organism_database_name}_core_*")
                    if len(org) > 1:
                        org = VerifyDatabase.only_keep_dir(org, session)
                    if len(org) != 1:
                        errors[i] = {f"Zero or many correct folder {ext}": org}
                    else:
                        data_files = [os.path.basename(j) for j in session.nlst(org[0])]
                        not_found = [db_key for db_key in DB.databases if db_key not in data_files]
                        # TODO: Check the number of columns of the databases in the server is exacly as expected
                        # without downloading all file. Problem the file is .gzipped. Instead, this is checked 
                        # at DatabaseManager.download_db() function.
                        if len(not_found) == 0:
                            proper_directory_structure.append(i)
                        else:
                            errors[i] = not_found
        except (socket.timeout, TimeoutError):
            raise TimeoutError(f"Problem with the connection to FTP server: {DB.ensembl_ftp_base}")
        return proper_directory_structure, errors


class DatabaseManager:

    """
    - Download databases
    - Creates necessary pd.DataFramaes by merging accordingly.
    """

    def __init__(self, organism: str, ensembl_release: int, local_repository: str):
        assert (os.path.isdir(local_repository) and
                os.access(local_repository, os.W_OK) and
                os.access(local_repository, os.R_OK))
        self.local_repository = local_repository
        self.ensembl_release = None
        self.set_ensembl_release(ensembl_release)
        self.organism = organism

    def set_ensembl_release(self, ensembl_release: int):
        assert ensembl_release > DB.earliest_ensembl_release
        self.ensembl_release = ensembl_release

    def download_db(self, db_key, redownload=False):
        """

        """
        output_path = os.path.join(self.local_repository, f"{self.organism}_{self.ensembl_release}_" + db_key)
        if not os.access(output_path, os.R_OK) or not os.path.isfile(output_path) or redownload:
            with ftplib.FTP(DB.ensembl_ftp_base, user="anonymous", passwd="") as session:
                ext = DB.ensembl_ftp_extension(self.ensembl_release)
                org = session.nlst(f"{ext}/{self.organism_database_name}_core_*")
                if len(org) > 1:
                    org = VerifyDatabase.only_keep_dir(org, session)
                assert len(org) == 1, ValueError(f"Multiple folders starting with: \'{self.organism}_core_*\'")
                url_database = os.path.join(org[0], db_key)
                with open(output_path, 'wb') as f:
                    session.retrbinary('RETR ' + url_database, f.write)
                with gzip.open(output_path, 'rt') as f:
                    if (f.readline().count(DB.delimiter) + 1) != len(DB.databases[db_key]["header"]):
                        raise ValueError(f"Downloaded database has unexpected number of columns: {db_key}")
        DB.databases[db_key][f"local_path_{self.organism}_{self.ensembl_release}"] = output_path

    def read_downloaded_db(self, database_key, usecols: list = None):
        df = pd.read_csv(DB.databases[database_key][f"local_path_{self.organism}_{self.ensembl_release}"],
                         compression='gzip', delimiter=DB.delimiter, on_bad_lines='error', low_memory=False,
                         names=DB.databases[database_key]["header"], usecols=usecols)
        return df

    def get_raw_db(self, database_key, usecols: list = None, redownload=False):
        self.download_db(database_key, redownload=redownload)
        return self.read_downloaded_db(database_key, usecols)

    def create_ids(self, form):
        assert form in ["gene", "transcript", "translation"]
        df = self.get_raw_db(f"{form}.txt.gz", ["stable_id", "version"], redownload=False)
        return df["stable_id"].astype(str) + "." + df["version"].astype(str)

    def create_relation(self):
        g = self.get_raw_db(f"gene.txt.gz", redownload=False,
                            usecols=["gene_id", "stable_id", "version"])
        t = self.get_raw_db(f"transcript.txt.gz", redownload=False,
                            usecols=["transcript_id", "gene_id", "stable_id", "version"])
        p = self.get_raw_db(f"translation.txt.gz", redownload=False,
                            usecols=["translation_id", "transcript_id", "stable_id", "version"])

        tgp = t.merge(g, how='left', on="gene_id", suffixes=("_t", "_g")  # validate="many_to_one",
                      ).merge(p, how='left', on="transcript_id", suffixes=("_tg", "_p"))  # validate="many_to_one",
        tgp.columns = ["transcript_id", "gene_id", "transcript_stable_id", "transcript_version",
                       "gene_stable_id", "gene_version", "translation_id",
                       "translation_stable_id", "translation_version"]
        return tgp

    def create_relation_archive(self):
        df = self.get_raw_db("gene_archive.txt.gz", usecols=None, redownload=False)
        df.drop(columns=["peptide_archive_id", "mapping_session_id"], inplace=True)
        return df

    def create_graph_id_history(self, form):
        s = self.get_raw_db("stable_id_event.txt.gz")
        m = self.get_raw_db("mapping_session.txt.gz")
        sm = pd.merge(s, m, how='outer', on="mapping_session_id")
        return sm[sm["type"] == form]

    def create_external_db(self, form):
        """
        Not exactly this but similar to the:
            SELECT g.stable_id, t.stable_id, tr.stable_id, x.dbprimary_acc, edb.db_name, es.synonym, ix.*
            FROM gene g
            JOIN transcript t USING (gene_id)
            JOIN translation tr USING (transcript_id)
            JOIN object_xref ox ON (g.gene_id = ox.ensembl_id AND ox.ensembl_object_type = "Gene")
            JOIN xref x ON (ox.xref_id = x.xref_id) ##
            LEFT JOIN external_db edb ON (x.external_db_id = edb.external_db_id)
            LEFT JOIN identity_xref ix ON (ox.object_xref_id = ix.object_xref_id)
            LEFT JOIN external_synonym es ON (x.xref_id = es.xref_id)
            LIMIT 10;

        alternatively
            FROM coord_system cs
            JOIN seq_region sr USING (coord_system_id)
            JOIN gene g USING (seq_region_id)

        Using the following:
            mysql --user=anonymous --host=ensembldb.ensembl.org -D homo_sapiens_core_105_38 -A

        http://www.germonline.org/info/using/api/core/schema/schema_description.html#identity_xref
        https://m.ensembl.org/info/docs/api/core/core_schema.html

        :param form:
        :return:
        """

        assert form in ["gene", "transcript", "translation"]
        a = self.get_raw_db(f"{form}.txt.gz", redownload=False,
                            usecols=[f"{form}_id", "stable_id", "version"])
        ox = self.get_raw_db("object_xref.txt.gz", redownload=False,
                             usecols=["ensembl_id", "ensembl_object_type", "xref_id", "object_xref_id"])
        x = self.get_raw_db("xref.txt.gz", redownload=False,
                            usecols=["xref_id", "external_db_id", "dbprimary_acc", "display_label"])
        ed = self.get_raw_db("external_db.txt.gz", redownload=False,
                             usecols=["external_db_id", "db_name", "db_display_name"])
        ix = self.get_raw_db("identity_xref.txt.gz", redownload=False,
                             usecols=["ensembl_identity", "xref_identity", "object_xref_id"])
        es = self.get_raw_db("external_synonym.txt.gz", redownload=False,
                             usecols=["xref_id", "synonym"])

        # make synonyms different lines display_label
        es = es.merge(x, validate="many_to_one", how="inner", on="xref_id")
        es.drop(columns=["display_label"], inplace=True)
        es.rename(columns={"synonym": "display_label"}, inplace=True)
        x = pd.concat([x, es], ignore_index=True)

        comb = pd.merge(a, ox[ox["ensembl_object_type"] == form.capitalize()], how='left', left_on=f"{form}_id", right_on="ensembl_id")  # validate="one_to_many"
        comb = comb.merge(x, how="left", on="xref_id")  # validate="many_to_many"
        comb = comb.merge(ed, how="left", on="external_db_id")  # validate="one_to_many"
        comb = comb.merge(ix, how="left", on="object_xref_id")  # validate="one_to_many"
        comb.drop(columns=["ensembl_id", "object_xref_id", "ensembl_object_type", "xref_id"], inplace=True)
        es.rename(columns={"stable_id": f"{form}_stable_id", "version": f"{form}_version"}, inplace=True)
        return comb

    def get_db(self, form, df_indicator, target_format="hdf5", read_format_from=None,
               create_even_if_exist=False, save_after_calculation=True, overwrite_even_if_exist=False):
        assert form in ["gene", "transcript", "translation", "all"]
        assert form != "all" or df_indicator not in ["relation" or "relation_archive"], \
            f"form=\'all\' is only valid when df_indicator in [\'relation\', \'relation_archive\']"
        hierarchy, file_path = self.file_name_saved(target_format, form, df_indicator)
        if read_format_from:
            df = self.get_db(form, df_indicator, target_format=read_format_from, read_format_from=None,
                             save_after_calculation=False, create_even_if_exist=False, overwrite_even_if_exist=False)
        elif not os.access(file_path, os.R_OK) or not os.path.isfile(file_path) or create_even_if_exist:
            if df_indicator == "external":
                df = self.create_external_db(form)
            elif df_indicator == "relation":
                df = self.create_relation()
            elif df_indicator == "relation_archive":
                df = self.create_relation_archive()
            elif df_indicator == "ids":
                df = self.create_ids(form)
            elif df_indicator == "graph_id_history":
                df = self.create_graph_id_history(form)
            else:
                raise ValueError("Unexpected entry for \'df_indicator\'.")
        else:
            df = self.read_exported_db(target_format, form, df_indicator)
        if save_after_calculation:
            self.export_db(df, form, df_indicator, target_format, overwrite=overwrite_even_if_exist)
        return df
        # TODO: TEST IT

    def read_exported_db(self, target_format: str, form: str, df_indicator: str):
        hierarchy, file_path = self.file_name_saved(target_format, form, df_indicator=df_indicator)
        assert os.access(file_path, os.R_OK) and os.path.isfile(file_path)
        if target_format == "hdf5":
            return pd.read_hdf(file_path, key=hierarchy)
        elif target_format == "csv":
            return pd.read_csv(header=True)
        elif target_format == "pickle":
            return pd.read_pickle(file_path)
        # TODO: TEST IT

    def file_name_saved(self, target_format: str, form: str, df_indicator: str):
        assert target_format in ["hdf5", "csv", "pickle"]
        hierarchy = f"ensembl_release_{self.ensembl_release}_{df_indicator}_{form}"
        if target_format == "hdf5":
            return hierarchy, os.path.join(self.local_repository, f"{self.organism}.h5")
        elif target_format == "csv":
            return None, os.path.join(self.local_repository, f"{self.organism}_{hierarchy}.csv")
        elif target_format == "pickle":
            return None, os.path.join(self.local_repository, f"{self.organism}_{hierarchy}.pickle")
        # TODO: TEST IT

    def export_db(self, df: pd.DataFrame, form: str, df_indicator, target_format: str, overwrite=False):
        hierarchy, file_path = self.file_name_saved(target_format, form, df_indicator=df_indicator)
        if not os.access(file_path, os.R_OK) or not os.path.isfile(file_path) or overwrite:
            if target_format == "hdf5" and hierarchy in file_path or overwrite:
                with pd.HDFStore(file_path, mode="a") as f:
                    f[hierarchy] = df
            elif target_format == "csv":
                df.to_csv(file_path, header=True, index=False)
            elif target_format == "pickle":
                df.to_pickle(file_path)
        # TODO: TEST IT


class GraphIDHistory:

    """
    - Creates ID history graph
    - 
    """

    def __init__(self, db_manager: DatabaseManager, form: str):
        assert form in ["gene", "transcript", "translation"]
        self.db_manager = db_manager
        self.form = form
        # TODO: Make this work only at the latest release, because it contains all connectivity information anyway.

    def construct_graph(self):
        df = self.db_manager.get_db(self.form, df_indicator="graph_id_history", target_format="hdf5")  # TODO: Test it
        g = nx.MultiDiGraph(name=f"{self.db_manager.organism}_{self.db_manager.ensembl_release}_{self.form}",
                            type=self.form,
                            ensembl_release=self.db_manager.ensembl_release,
                            organism=self.db_manager.organism)
        for ind, e in df.iterrows():
            nv = e["new_version"]
            ov = e["old_version"]
            nv = 0 if nv == "\\N" else int(nv)
            ov = 0 if ov == "\\N" else int(ov)
            nsi = e['new_stable_id']
            osi = e['old_stable_id']

            _oih = [0, "\\N"]
            assert nv not in _oih or ov not in _oih, "Entry with stable ID version \'0\' for both nodes!."
            assert osi != "\\N" or nsi != "\\N", "Entry with unnamed stable ID!."
            assert not (ov > 0 and osi == "\\N"), "Entry with stable ID version but unnamed ID"
            assert not (nv > 0 and nsi == "\\N"), "Entry with stable ID version but unnamed ID"

            no_old_node_id = "Void"
            no_new_node_id = "Retired"
            old_node_name = f"{osi}.{ov}" if ov > 0 else f"{nsi}.{no_old_node_id}"
            new_node_name = f"{nsi}.{nv}" if nv > 0 else f"{osi}.{no_new_node_id}"

            edge_attributes = {i: str(e[i]) for i in ["old_db_name", "old_assembly",
                                                      "new_db_name", "new_assembly"]}
            edge_attributes.update({i: float(e[i]) for i in ["old_release", "new_release"]})
            edge_attributes.update({"weight": float(e["score"]),  # IMPORTANT 0 means no data
                                    "mapping_session_id": int(e["mapping_session_id"]),
                                    "created": e["created"]})
            g.add_edge(old_node_name, new_node_name, **edge_attributes)

        # TODO: Add attributes 'latest=True' to the nodes which are present at the latest ensembl release, 
        # all others 'latest=False'
        return g

    def get_graph(self, target_format="pickle", read_format_from=None,
                  create_even_if_exist=False, save_after_calculation=True, overwrite_even_if_exist=False):
        file_path = self.file_name_saved(target_format)
        if read_format_from:
            g = self.get_graph(target_format=read_format_from, read_format_from=None,
                               save_after_calculation=False, create_even_if_exist=False, overwrite_even_if_exist=False)
        elif not os.access(file_path, os.R_OK) or not os.path.isfile(file_path) or create_even_if_exist:
            g = self.construct_graph()
        else:
            g = self.read_exported_graph(target_format)
        if save_after_calculation:
            self.export_graph(g, target_format, overwrite=overwrite_even_if_exist)
        return g

    def read_exported_graph(self, target_format: str):
        file_path = self.file_name_saved(target_format)
        assert os.access(file_path, os.R_OK) and os.path.isfile(file_path)
        if target_format == "graphml":
            return nx.read_graphml(file_path)
        elif target_format == "pickle":
            return nx.read_gpickle(file_path)
        elif target_format == "gml":
            return nx.read_gml(file_path)

    def file_name_saved(self, target_format: str):
        assert target_format in ["graphml", "pickle", "gml"]
        ext = f"ensembl_release_{self.db_manager.ensembl_release}_{self.form}"
        if target_format == "graphml":
            return os.path.join(self.db_manager.local_repository, f"{self.db_manager.organism}_{ext}.graphml")
        elif target_format == "pickle":
            return os.path.join(self.db_manager.local_repository, f"{self.db_manager.organism}_{ext}.pickle")
        elif target_format == "gml":
            return os.path.join(self.db_manager.local_repository, f"{self.db_manager.organism}_{ext}.gml")

    def export_graph(self, g: nx.MultiDiGraph, target_format, overwrite=False):
        file_path = self.file_name_saved(target_format)
        if not os.access(file_path, os.R_OK) or not os.path.isfile(file_path) or overwrite:
            if target_format == "graphml":
                nx.write_graphml(g, file_path)
            elif target_format == "pickle":
                nx.write_gpickle(g, file_path)
            elif target_format == "gml":
                nx.write_gml(g, file_path)

    def draw_tree_with_id(self):
        # For visualization of a single tree
        # https://networkx.org/documentation/stable/reference/algorithms/traversal.html
        pass

    def convert_history(self, from_id, to_release):
        pass
        # from_id: ensembl_id_version
        # to_release: target ensembl release, it can be "latest"
        # Use edge weight to get the best matching conversion (highest score)
            # Note: some edges has no weight (0 means no data)
        # Check following links:
            # https://www.ensembl.org/Homo_sapiens/Gene/Idhistory?db=core;g=ENSG00000000460;r=1:169662007-169854080
            # https://www.ensembl.org/Homo_sapiens/Gene/Idhistory?db=core;g=ENSG00000100239;r=22:50343304-50445090
            # https://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000100239;r=22:50343304-50445090
            # Best example: https://www.ensembl.org/Homo_sapiens/Gene/Idhistory?db=core;g=ENSG00000206461;r=CHR_HSCHR6_MHC_QBL_CTG1:31103629-31104965;t=ENST00000383532
        

    def convert_form(self, from_id, to_form):
        pass
        # given: target form (option to convert trancripts/proteins to gene_ids for example)
        # For example, given gene_id_version, get_transcript_id_version
        # Use the dataframes creates by DatabaseManager: gene_archieve plus latest_relation 
        
    def update_graph_with_the_new_release(self):
        # When new release arrive, just add new nodes.
        pass


class IdentifyDataset:
    
    def calculate_dataset_score():
    """
    given: list_of_id

    for f in forms:  # if form is provided by the use skip.
        for ens_release in available_ens_releases:
            for db in comb (see DatabaseManager.create_external_db)
                for j in db:
                    -> create scoring based on similarity to two sets of ids (ids in j and list_of_id)
                        e.g. check how of list_of_id represented in j

    report best scoring dataset, release, form
    """
    pass

    def convert_ensembl_id_version():
    # given: ens_release, ens_dataset: using calculate_dataset_score
    # given: list_of_id
    # get corresponding dataframe by DatabaseManager.create_external_db
    # report matching ensembl_ids for list_of_id
    pass


class Controller:

    def id_history_voyager(organism_input, list_of_id, target_form, target_release):

        """
        vdf = VerifyDatabase(organism_input)
        available_ensembl_releases by VerifyDatabase
        latest_ensembl_release by VerifyDatabase

        ## at initial run only, to create the necessary hdf5 file in the local/cloud
        ## or if new ensembl release published, run only with the new one.
        for i in available_ensembl_releases:
            dm = DatabaseManager(organism_database, i, repository)
            for f in [gene, transcript, translation]
                for dfi in df_indicatorss:
                    dm.get_db(form, dfi)
        
        if graph exist:
            check if it is created with latest relase
            if not update if so read
        else:
            create graph at latest_ensembl_release
        
        IdentifyDataset.calculate_dataset_score(list_of_id)
        IdentifyDataset.convert_ensembl_id_version(list_of_id)

        ########## Version 1: first convert target_form then move in the graph
        GraphIDHistory.convert_form(target_form)
        GraphIDHistory.convert_history (using target_release): go through the graph of given form
        return
        ########## Version 2: first move in the graph then convert target_form
        GraphIDHistory.convert_form(target_form)
        GraphIDHistory.convert_history (using target_release): go through the graph of given form
        return
        """
        pass




# transcript_name
# gene_name
# protein_name
# uniprot ids
# refseq gene
# refseq transcript
# refseq protein
# pdb
# hgnc
# many many more!






# vdf = VerifyDatabase("human")
# organism_database = vdf.organism_database_name
# latest_ensembl_release = vdf.latest_ensembl_release
# dm = DatabaseManager(organism_database, latest_ensembl_release, local_repository="/Users/kemalinecik/Downloads")
# G = GraphIDHistory(dm, form="gene")
# g = GraphIDHistory(dm)




# NOTES FOR ME:
# todo: kendi içine gidenler
# ENSG00000000460	17	ENSG00000000460	17	408	gene	0.982409
# todo: node attributeleri güncelleniyor çok salakça oluyor
# todo: new ve old node özellikleri birleşiyor: node'da hem yeni hem eski att'lar var
# \N	0	ENSG00000100239	2	356	gene	0
# ENSG00000100239	1	ENSG00000100239	1	352	gene	0
# ENSG00000100239	1	ENSG00000100239	2	355	gene	0

## INTEGRATION OF FOLLOWINGS?? 
# unmapped_object, unmapped_reason, dependent_xref

# TODO: IMPLEMENT that
#  https://stackoverflow.com/questions/9522877/pythonic-way-to-have-a-choice-of-2-3-options-as-an-argument-to-a-function/9523071
```

**Comment by davidsebfischer** [comment]
Outline: This functionality will be called in https://github.com/theislab/sfaira/blob/f79e1ff50f2662d338dd530c2a872c7fa380536a/sfaira/data/dataloaders/base/dataset.py#L559, we can add kwargs to that function accordingly, let's try not overdo this though to keep the interface simple. This function takes a anndata instance that is already loaded as `self.adata` with known location of gene IDs and:

- imputes missing symbols or IDs if only one given (https://github.com/theislab/sfaira/blob/f79e1ff50f2662d338dd530c2a872c7fa380536a/sfaira/data/dataloaders/base/dataset.py#L706)
- broadcasts the var axis to the desired feature space, eg all genes in an assembly (https://github.com/theislab/sfaira/blob/f79e1ff50f2662d338dd530c2a872c7fa380536a/sfaira/data/dataloaders/base/dataset.py#L704)

In this function, `target_ids`,  `target_symbols`, and `allowed_ids` are defined by a GenomeContainer instance, this is a shallow wrapper around an assembly giving us access to ordered lists of genes. I would propose we address imputation of identifiers in this method https://github.com/theislab/sfaira/blob/f79e1ff50f2662d338dd530c2a872c7fa380536a/sfaira/data/dataloaders/base/dataset.py#L522, note that right now we are using a dict as a map, eg. `self.genome_container.id_to_symbols_dict`, we can consider replacing this by a new method in the GenomeContainer, or by a direct interface here. In the GC might be more intuitive.

Broadcasting https://github.com/theislab/sfaira/blob/f79e1ff50f2662d338dd530c2a872c7fa380536a/sfaira/data/utils.py#L146, is  based on shuffling of columns and adding of zero columns right now, ie assumes 1:1 ID maps. This we could enrich by one:many etc mapping information, ie here also the kwargs of the function might change.
