### ISSUE TITLE
store data memory footprint in meta data

### ISSUE THREAD

**Issue by davidsebfischer** [theislab/sfaira#69]
We could use this to anticipate memory load in parallelised loading and to make sure large data sets are not loaded in parallel.

- [ ] can we access the object memory footprint from within python
- [ ] store in meta data
- [ ] access this during parallelised DatasetGroup loading
- [ ] add prooperty to DatasetGroup with maximum expected memory requirements
