### ISSUE TITLE
allow cell-wise meta data to be on data set group level

### ISSUE THREAD

**Issue by davidsebfischer** [theislab/sfaira#92]
Do this optional so that mapping .csvs can be generated separately for each member (current) or centrally once for entire group.

- [x] distinguish both cases in writing
- [x] collect cell types to map from all files in central case
- [x] distinguish both cases in reading
- [x] annotate in docs
